---
version: "3.7"

services:
  phpliteadmin:
    # https://bitbucket.org/phpliteadmin/public/wiki/Installation
    image: 'jennerwein/phpliteadmin'
    container_name: "phpliteadmin"
    volumes:
      - "./db:/db"
    ports:
      - "8080:80"
    environment:
      - TZ=Europe/Berlin
      - PASSWORD=mypass
